[package]
name = "xlsx_reader"
version = "3.1.1"
edition = "2021"
authors = ["OZ <normandiggs@gmail.com>"]
description = "Reader of XLSX files (only data)"
license = "MIT"
repository = "https://github.com/e-oz/xlsx_reader"

[dependencies]
serde-xml-rs = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
zip = "0.6.6"
